spring:
  application:
    name: Swager Test
  datasource:
    url: jdbc:mysql://localhost/test?
    username: root
    password: local
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
server:
  port: 9090

springfox:
  documentation:
    swaggerUi:
      baseUrl: /documentation
    openApi:
      v3:
        path: /documentation/v3/api-docs
    swagger:
      v2:
        path: /documentation/v2/api-docs
